name: CI
on: [push, workflow_dispatch]
jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Test
        run: npm run test-ci
      - name: Badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
